### ISSUE TITLE
Missing environment file when running node helpers showcase

### ISSUE THREAD

**Issue by skyegalaxy** [UrbanMachine/node_helpers#2]
Hey, great to see this project getting off the ground! It seems that there may have been an issue porting from the monorepo in that it looks like a .env file is missing. 

```
:~/Source Code (Desktop)/repos/node_helpers$ docker/launch node_helpers_showcase
docker/_shared.sh: line 4: .env: No such file or directory
```

**Comment by apockill** [comment]
Awesome, good catch! Can you check if it's working now? Feel free to close the issue if it's working :tada: 

PS- I haven't fleshed out the showcase project (at all) yet, but hopefully soon I'll have something cool to show off some of the features.

**Comment by skyegalaxy** [comment]
yup, looks like the container builds, launches, and opens an rviz window now! Thanks for fixing it.

**Comment by apockill** [comment]
Awesome! :tada:
